'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Search, Download, Star, FileText, Calculator, CheckCircle, Zap, Crown, Users } from 'lucide-react';

interface MarketplaceProduct {
  id: string;
  title: string;
  description: string;
  type: 'template' | 'calculator' | 'checklist' | 'guide' | 'contract';
  price: number;
  rating: number;
  downloads: number;
  tags: string[];
  aiGenerated: boolean;
  featured: boolean;
}

const products: MarketplaceProduct[] = [
  {
    id: '1',
    title: 'Professional Roof Inspection Checklist',
    description: 'Comprehensive 47-point inspection checklist generated by Claude, covering all major roofing systems and common issues.',
    type: 'checklist',
    price: 29,
    rating: 4.9,
    downloads: 1247,
    tags: ['inspection', 'checklist', 'professional'],
    aiGenerated: true,
    featured: true
  },
  {
    id: '2',
    title: 'Material Cost Calculator 2024',
    description: 'Dynamic pricing calculator with real-time market data integration, covering 200+ roofing materials.',
    type: 'calculator',
    price: 79,
    rating: 4.9,
    downloads: 2103,
    tags: ['calculator', 'pricing', 'materials'],
    aiGenerated: true,
    featured: true
  }
];

export default function MarketplacePage() {
  const [searchTerm, setSearchTerm] = useState('');

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'template': return <FileText className="w-5 h-5" />;
      case 'calculator': return <Calculator className="w-5 h-5" />;
      case 'checklist': return <CheckCircle className="w-5 h-5" />;
      case 'guide': return <Users className="w-5 h-5" />;
      default: return <FileText className="w-5 h-5" />;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900">
      <div className="bg-black/20 backdrop-blur-sm border-b border-white/10">
        <div className="container mx-auto px-6 py-8">
          <h1 className="text-4xl font-bold text-white text-center mb-4">
            AI Market<span className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">place</span>
          </h1>
          <p className="text-xl text-slate-300 text-center max-w-2xl mx-auto">
            Professional roofing documents generated by Claude AI
          </p>
        </div>
      </div>

      <div className="container mx-auto px-6 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {products.map((product) => (
            <div key={product.id} className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-all">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-blue-500/20 rounded-lg text-blue-400">
                    {getTypeIcon(product.type)}
                  </div>
                  {product.featured && (
                    <div className="flex items-center gap-1 px-2 py-1 bg-gradient-to-r from-yellow-500/20 to-orange-500/20 rounded-full">
                      <Crown className="w-3 h-3 text-yellow-400" />
                      <span className="text-xs text-yellow-300 font-medium">Featured</span>
                    </div>
                  )}
                </div>
                <div className="flex items-center gap-1">
                  <Star className="w-4 h-4 text-yellow-400 fill-current" />
                  <span className="text-sm text-slate-300">{product.rating}</span>
                </div>
              </div>

              <h3 className="text-xl font-bold text-white mb-3">{product.title}</h3>
              <p className="text-slate-300 text-sm mb-4">{product.description}</p>

              <div className="flex items-center justify-between pt-4 border-t border-white/10">
                <span className="text-2xl font-bold text-white">${product.price}</span>
                <button className="px-4 py-2 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg hover:shadow-lg transition-all">
                  Buy Now
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}