name: CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Install Node and enable npm caching
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint source
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run unit tests
        run: npm run test

        - name: Install Playwright browsers
      run: npx playwright install --with-deps
  - name: Run e2e tests
        run: npm run test:e2e

      - name: Build application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next

      - name: Slack failure notification
            continue-on-error: true
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Email failure notification
        if: failure()
           continue-on-error: true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI workflow failed"
          body: "The CI job failed. See GitHub Actions for details."
          to: ${{ secrets.ALERT_EMAIL }}
          from: ci@myroofgenius.com
