name: Production Health Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
    - name: Check Health API
      run: |
        curl -f https://www.myroofgenius.com/api/health || exit 1
