name: Scheduled Maintenance

on:
  schedule:
    # Nightly DB backup at 02:00 UTC
    - cron: '0 2 * * *'
    # Weekly cleanup every Sunday at 04:00 UTC
    - cron: '0 4 * * 0'

jobs:
  db-backup:
    if: github.event.schedule == '0 2 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login

      - name: Perform database backup
        run: supabase db dump -f backup_$(date +%F).sql

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backup_*.sql

      - name: Slack failure notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Email failure notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Nightly backup failed"
          body: "Supabase backup job failed."
          to: ${{ secrets.ALERT_EMAIL }}
          from: ci@myroofgenius.com

  cleanup-downloads:
    if: github.event.schedule == '0 4 * * 0'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup expired downloads
        run: curl -f https://myroofgenius.com/api/cron/cleanup-expired-downloads

      - name: Slack failure notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Email failure notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Download cleanup failed"
          body: "Cleanup job failed to run."
          to: ${{ secrets.ALERT_EMAIL }}
          from: ci@myroofgenius.com
