name: Validate DB Schema
on: [push, pull_request]
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g supabase
    - run: supabase db lint
