name: Migrations Validator

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop, feature/**]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login

      - name: Check migration status
        run: supabase migration status

      - name: Slack failure notification
        if: failure()
        uses: 8398a7/action-slack@v3
        continue-on-error: true
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Email failure notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        continue-on-error: true
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Migration check failed"
          body: "Pending or broken migrations detected."
          to: ${{ secrets.ALERT_EMAIL }}
          from: ci@myroofgenius.com
